### ISSUE TITLE
Failed to Resolve

### ISSUE THREAD

**Issue by cs-abdulwahab** [farhanahmed95/HttpFileRequest#1]
When added as a Gradle Dependency 
error :  Failed to Resolve

**Comment by farhanahmed95** [comment]
did you add this in your build.gradle file?
`repositories {
    maven {
        url 'https://dl.bintray.com/farhanahmed95/maven/'
    }
}`

working totally fine on my side.

**Comment by cs-abdulwahab** [comment]
got it
Thanks
